app:
  name: ScreenerApp
  version: '1.0'
screener:
- columns:
  - Perf.1M
  - Perf.3M
  - Perf.YTD
  - Perf.Y
  - Perf.5Y
  - Perf.All
  - beta_1_year
  - beta_3_year
  - beta_5_year
  - Volatility.D
  - Volatility.W
  - Volatility.M
  - Recommend.All
  - Recommend.MA
  - Recommend.Other
  - RSI
  - AO
  - CCI20
  - close
  - open
  - volume
  - change_percent
  descripcion: Obtiene una lista de símbolos desde una watchlist de TradingView y
    muestra su rendimiento.
  nombre: Dr Market - v.2ba 👽
  tipo: tv_watchlist
  url: https://www.tradingview.com/watchlists/162767447/
- columns:
  - Perf.W
  - Perf.3M
  - Perf.YTD
  descripcion: Obtiene una lista de símbolos desde una watchlist de TradingView y
    muestra su rendimiento.
  nombre: Dr. Market - Small and Mid Caps
  tipo: tv_watchlist
  url: https://es.tradingview.com/watchlists/139799472/
- nombre: Screener Nasdaq Completo
  descripcion: Obtiene una lista de símbolos desde nasdaq
  tipo: nasdaq_screener
- tipo: tv_watchlist
  nombre: Dr. Market - GSTMTAIP
  descripcion: ' AI basket'
  url: https://es.tradingview.com/watchlists/152268890/
  columns:
  - Perf.W
  - Perf.1M
  - Perf.3M
  - Perf.YTD
  - Perf.Y
  - Perf.5Y
  - Recommend.All
- tipo: tv_watchlist
  nombre: Dr Market IBD IPO
  descripcion: ''
  url: https://www.tradingview.com/watchlists/146554119/
  columns:
  - Perf.W
  - Perf.1M
  - Perf.3M
  - Perf.YTD
  - Perf.Y
  - Perf.5Y
  - Recommend.All
dashboard:
  num_columnas: 2
  widget:
    Gráfico AAPL:
      ticker: AAPL
      interval: 1d
      show_volume: false
      height: 350
      period: 1y
      type: chart
      position: 2
      is_dark: true
    Grafico SPX:
      ticker: ^SPX
      interval: 1m
      show_volume: false
      height: 350
      period: 1d
      type: chart
      position: 3
      is_dark: true
    Fear & Greed:
      url: https://production.dataviz.cnn.io/index/fearandgreed/graphdata
      height: 350
      line_color: '#1f77b4'
      bg_color: '#ffffff'
      text_color: '#000000'
      type: feargreed
      position: 1
      is_dark: true
    Day Gainers:
      query_mode: day_gainers
      custom_query: ''
      offset: 0
      size: 10
      sortField: regular_market_change
      sortAsc: false
      height: 350
      type: screen
      position: 0
      is_dark: true
    Frases:
      lang: es
      height: 300
      type: quote
      position: 4
    Donaciones:
      mode: html
      content: '<a href="https://www.buymeacoffee.com/fiambre" target="_blank"><img
        src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy
        Me A Coffee" style="height: 60px !important;width: 217px !important;" ></a>'
      type: custom_content
      position: 5
      is_dark: true
