name: Build and Package Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Download and extract Python 3.12.8 embedded
      - name: Download Python 3.12.8 embedded
        run: |
          curl -L -o python-embedded.zip https://www.python.org/ftp/python/3.12.8/python-3.12.8-embed-amd64.zip
          mkdir dist\python
          tar -xf python-embedded.zip -C dist\python

      # Enable pip for embedded Python 3.12.8
      - name: Enable pip for Python 3.12.8 embedded
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          dist\python\python.exe get-pip.py
          del get-pip.py

      # Modify python312._pth to enable 'site-packages'
      - name: Modify python312._pth
        run: |
          powershell -Command "(Get-Content dist\python\python312._pth) -replace '^#import site', 'import site' | Set-Content dist\python\python312._pth"

      # Manually install setuptools and wheel (required for package installations)
      - name: Install setuptools and wheel
        run: |
          dist\python\python.exe -m pip install --upgrade setuptools wheel

      # Install app requirements using embedded Python 3.12.8
      - name: Install app requirements
        run: |
          dist\python\python.exe -m pip install -r requirements.txt

      # Copy the app folder to the dist directory
      - name: Copy app folder to dist
        run: |
          xcopy app dist\app /E /I
          xcopy win.py dist\
        
      # Manually install setuptools and wheel (required for package installations)
      - name: Unzip run exe
        run: |
          tar -xf extras\run.zip -C dist\
      - name: Unzip vclibs
        run: |
          mkdir dist\python\Lib\site-packages\sklearn\.libs 2>nul
          tar -xf extras\vclibs.zip -C dist\python\Lib\site-packages\sklearn\.libs
      # Publish the zip package as an artifact
      - name: Upload zip package
        uses: actions/upload-artifact@v4
        with:
          name: XungungoPackage
          path: dist\
